### ISSUE TITLE
Reimplement survey?

### ISSUE THREAD

**Issue by molarmanful** [wenogk/biotechsurvey#2]
Less dependencies = simpler + easier to manage

**Comment by wenogk** [comment]
I think the surveyjs library is easier to use pluss it has this drag n drop form builder, [https://surveyjs.io/Survey/Builder/](https://surveyjs.io/Survey/Builder/) so we wouldn't be using our time making the form but instead making the personal content using the form choices

**Comment by molarmanful** [comment]
Sounds good
